import { Link, useNavigate } from 'react-router'
import { Archive, ArrowUpRight, CalendarClock, Ellipsis, ListTodo, Pencil, Settings2, Star, Users } from 'lucide-react'
import { MotionCard } from '@/components/common/motion'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback, AvatarGroup, AvatarGroupCount, AvatarImage } from '@/components/ui/avatar'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { formatRelativeDate } from '@/utils/format-relative-date'
import type { HomeBoard } from '../services/home-service'
import { BoardIcon } from './board-style-fields'

export function HomeBoardCard({ board, view, avatarUrls, onFavorite, onEdit, onMembers, onSettings, onArchive }: { board: HomeBoard; view: 'grid' | 'list'; avatarUrls: Record<string, string>; onFavorite: () => void; onEdit: () => void; onMembers: () => void; onSettings: () => void; onArchive: () => void }) {
  const navigate = useNavigate()
  const canManage = board.access_role === 'owner' || board.access_role === 'admin'
  const progress = board.task_count ? Math.round(board.completed_count / board.task_count * 100) : 0
  return <MotionCard className={`relative min-w-0 overflow-hidden border-border/80 ${view === 'list' ? 'p-4 sm:p-5' : 'flex min-h-52 flex-col p-4 sm:p-5'}`}>
    <span className="absolute inset-y-0 left-0 w-[2px]" style={{ background: board.color }} />
    <div className={`flex min-w-0 gap-3 ${view === 'list' ? 'items-center' : 'items-start'}`}>
      <div className="grid size-10 shrink-0 place-items-center rounded-lg border border-border bg-surface-raised" style={{ color: board.color }}><BoardIcon name={board.icon} className="size-5" /></div>
      <div className="min-w-0 flex-1"><Link to={`/app/board/${board.id}`} className="group inline-flex max-w-full items-center gap-2"><h3 className="truncate text-sm font-semibold tracking-tight sm:text-base">{board.name}</h3><ArrowUpRight className="size-3.5 shrink-0 text-muted-foreground transition-colors group-hover:text-cyan" /></Link><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-muted-foreground">{board.description || 'Sem descrição'}</p></div>
      <div className="flex shrink-0 items-center gap-1"><Button variant="ghost" size="icon-sm" aria-label={board.favorite ? `Remover ${board.name} dos favoritos` : `Favoritar ${board.name}`} aria-pressed={board.favorite} onClick={onFavorite} className={board.favorite ? 'text-warning' : 'text-muted-foreground'}><Star className={`size-4 ${board.favorite ? 'fill-current' : ''}`} /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Ações de ${board.name}`}><Ellipsis className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => navigate(`/app/board/${board.id}`)}>Abrir quadro</DropdownMenuItem><DropdownMenuItem onSelect={onFavorite}>{board.favorite ? 'Remover favorito' : 'Favoritar'}</DropdownMenuItem>{canManage && <><DropdownMenuSeparator /><DropdownMenuItem onSelect={onEdit}><Pencil className="size-4" /> Editar</DropdownMenuItem><DropdownMenuItem onSelect={onMembers}><Users className="size-4" /> Membros</DropdownMenuItem><DropdownMenuItem onSelect={onSettings}><Settings2 className="size-4" /> Configurações</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onSelect={onArchive} className="text-destructive"><Archive className="size-4" /> Arquivar</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>
    </div>
    <div className={`${view === 'list' ? 'mt-3 sm:ml-14' : 'mt-auto pt-5'} min-w-0`}><div className="mb-2 flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><ListTodo className="size-3.5" />{board.task_count} {board.task_count === 1 ? 'tarefa' : 'tarefas'}</span><span>{progress}% concluído</span></div><div role="progressbar" aria-label={`Progresso de ${board.name}`} aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} className="h-1 overflow-hidden rounded-full bg-surface-raised"><span className="block h-full rounded-full transition-[width] duration-200" style={{ width: `${progress}%`, background: board.color }} /></div><div className="mt-4 flex items-center justify-between gap-2 border-t border-border/70 pt-3 text-[11px] text-muted-foreground"><div className="flex min-w-0 items-center gap-3"><AvatarGroup>{board.members.slice(0, 3).map(member => <Avatar key={member.id} size="sm" title={member.name}><AvatarImage src={member.avatar_url ? avatarUrls[member.avatar_url] : undefined} alt="" /><AvatarFallback className="bg-surface-raised text-[9px]">{(member.name || '?').slice(0, 2).toUpperCase()}</AvatarFallback></Avatar>)}{board.member_count > 3 && <AvatarGroupCount className="size-6 text-[9px]">+{board.member_count - 3}</AvatarGroupCount>}</AvatarGroup><span className="inline-flex items-center gap-1"><Users className="size-3" />{board.member_count}</span></div><span className="inline-flex min-w-0 max-w-[55%] items-center gap-1"><CalendarClock className="size-3" /><span className="hidden sm:inline">Atividade </span><span className="truncate">{formatRelativeDate(board.last_activity)}</span></span></div></div>
  </MotionCard>
}
