[functions.admin-update-user]
verify_jwt = true

[functions.admin-reset-user-password]
verify_jwt = true

[functions.workspace-create-member]
verify_jwt = true

[functions.workspace-update-member]
verify_jwt = true
